<?php

declare(strict_types=1);

namespace Liip\MetadataParser\TypeResolver;

use PHPStan\PhpDocParser\Ast\Type\ArrayTypeNode;
use PHPStan\PhpDocParser\Ast\Type\GenericTypeNode;
use PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode;
use PHPStan\PhpDocParser\Ast\Type\NullableTypeNode;
use PHPStan\PhpDocParser\Ast\Type\TypeNode;
use PHPStan\PhpDocParser\Ast\Type\UnionTypeNode;
use PHPStan\PhpDocParser\Lexer\Lexer;
use PHPStan\PhpDocParser\Parser\ConstExprParser;
use PHPStan\PhpDocParser\Parser\TokenIterator;
use PHPStan\PhpDocParser\Parser\TypeParser;
use PHPStan\PhpDocParser\ParserConfig;
use Symfony\Component\TypeInfo\Exception\UnsupportedException;
use Symfony\Component\TypeInfo\Type;
use Symfony\Component\TypeInfo\Type\CollectionType;
use Symfony\Component\TypeInfo\Type\GenericType;
use Symfony\Component\TypeInfo\Type\NullableType;
use Symfony\Component\TypeInfo\Type\UnionType;
use Symfony\Component\TypeInfo\TypeContext\TypeContext;
use Symfony\Component\TypeInfo\TypeResolver\TypeResolverInterface;

/**
 * The StringTypeResolver from symfony automatically adds a key to collections, which means that an initial type
 * of `array<string>` is converted to `array<int|string, string>`, but this removes the possibility to know whether
 * the user actually wanted to use a hashmap or a simple array, which is important for serialization.
 *
 * Given the following array in php:
 *
 * ```php
 * ['foo', 'bar', 'foobar']
 * ```
 *
 * with the type that is generated by the symfony resolver we would mark this as a hashmap which would serialize
 * to the following:
 *
 * ```json
 * {
 *   "0": "foo",
 *   "1": "bar",
 *   "2": "foobar"
 * }
 * ```
 *
 * but the initial intention was to serialize it as a simple array:
 *
 * ```json
 * [
 *   "foo",
 *   "bar",
 *   "foobar"
 * ]
 * ```
 *
 * This new type resolver tackles this issue by checking the original value to see what was actually intended.
 *
 * @internal
 */
final readonly class LiipStringTypeResolver implements TypeResolverInterface
{
    private Lexer $lexer;

    private TypeParser $parser;

    public function __construct(
        private TypeResolverInterface $typeResolver,
        ?Lexer $lexer = null,
        ?TypeParser $parser = null,
    ) {
        if (class_exists(ParserConfig::class)) {
            $this->lexer = $lexer ?? new Lexer(new ParserConfig([]));
            $this->parser = $parser ?? new TypeParser($config = new ParserConfig([]), new ConstExprParser($config));
        } else {
            $this->lexer = $lexer ?? new Lexer();
            $this->parser = $parser ?? new TypeParser(new ConstExprParser());
        }
    }

    public function resolve(mixed $subject, ?TypeContext $typeContext = null): Type
    {
        if ($subject instanceof \Stringable) {
            $subject = (string) $subject;
        } elseif (!\is_string($subject)) {
            throw new UnsupportedException(\sprintf('Expected subject to be a "string", "%s" given.', get_debug_type($subject)), $subject);
        }

        $tokens = new TokenIterator($this->lexer->tokenize($subject));
        $node = $this->parser->parse($tokens);

        $symfonyType = $this->typeResolver->resolve($subject, $typeContext);

        return $this->normalize($node, $symfonyType, $typeContext);
    }

    private function normalize(?TypeNode $node, Type $symfonyType, ?TypeContext $typeContext): Type
    {
        if (null === $node) {
            return $symfonyType;
        }

        if ($symfonyType instanceof NullableType) {
            return Type::nullable($this->normalize($this->removeNullNodes($node), $symfonyType->getWrappedType(), $typeContext));
        }

        if ($symfonyType instanceof UnionType && $node instanceof UnionTypeNode) {
            $unionTypes = [];
            foreach ($node->types as $memberNode) {
                if ($this->isNullNode($memberNode)) {
                    continue;
                }

                $memberType = $this->typeResolver->resolve((string) $memberNode, $typeContext);
                $unionTypes[] = $this->normalize($memberNode, $memberType, $typeContext);
            }

            return Type::union(...$unionTypes);
        }

        if (!$symfonyType instanceof CollectionType) {
            return $symfonyType;
        }

        if (!$node instanceof ArrayTypeNode && !$node instanceof GenericTypeNode) {
            return $symfonyType;
        }

        $valueType = $this->normalize($this->getCollectionValueNode($node), $symfonyType->getCollectionValueType(), $typeContext);

        if ($symfonyType->isList()) {
            return Type::list($valueType);
        }

        $wrappedType = $symfonyType->getWrappedType();
        $mainType = $wrappedType instanceof GenericType ? $wrappedType->getWrappedType() : $wrappedType;

        if (!$this->hasKey($node)) {
            return Type::collection(Type::generic($mainType, $valueType));
        }

        return Type::collection($mainType, $valueType, $symfonyType->getCollectionKeyType());
    }

    private function removeNullNodes(TypeNode $node): TypeNode
    {
        if ($node instanceof NullableTypeNode) {
            return $node->type;
        }

        if (!$node instanceof UnionTypeNode) {
            return $node;
        }

        $nonNull = array_values(array_filter($node->types, fn (TypeNode $type): bool => !$this->isNullNode($type)));

        return 1 === \count($nonNull) ? $nonNull[0] : new UnionTypeNode($nonNull);
    }

    private function isNullNode(TypeNode $node): bool
    {
        return $node instanceof IdentifierTypeNode && 'null' === strtolower($node->name);
    }

    private function getCollectionValueNode(ArrayTypeNode|GenericTypeNode $node): TypeNode
    {
        if ($node instanceof ArrayTypeNode) {
            return $node->type;
        }

        // The value is always the last generic argument (`array<V>` or `array<K, V>`).
        return $node->genericTypes[array_key_last($node->genericTypes)];
    }

    private function hasKey(ArrayTypeNode|GenericTypeNode $node): bool
    {
        return !$node instanceof ArrayTypeNode && \count($node->genericTypes) > 1;
    }
}
